/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mgrouse.downtimebot;

import net.dv8tion.jda.api.events.GenericEvent;
import net.dv8tion.jda.api.hooks.EventListener;


public class DownTimeBot implements EventListener
{

    public static void main(String[] args)
    {
	;
    }

    @Override
    public void onEvent(GenericEvent event)
    {
	// TODO Auto-generated method stub

    }
}
